image:
  name: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/common/build:kaniko-debug
  entrypoint: [""]

variables:
  ECR_BASE_URL: 202949997891.dkr.ecr.ap-northeast-2.amazonaws.com
  AWS_REGION: "ap-northeast-2"
 
stages:
  - package

.template-prepare-ecr:
  script:
    # AWS ECR Login
    - export IS_REPO=`aws ecr describe-repositories --region ${AWS_REGION} --query "repositories[].repositoryName" | grep ${DEST_ECR_IMAGE_REPO} | wc -l`
    - echo $IS_REPO $DEST_ECR_IMAGE_REPO
    - >
      if [ "$IS_REPO" == "0" ]; then
        aws ecr create-repository --repository-name ${DEST_ECR_IMAGE_REPO} --region ${AWS_REGION} --image-scanning-configuration scanOnPush=true
      fi

.template-docker-build:
  script:    
    ### Check Latest Image
    - export IS_LATEST=`aws ecr describe-images --region ${AWS_REGION} --repository-name ${DEST_ECR_IMAGE_REPO} --query imageDetails[].imageTags | grep ${DEST_ECR_IMAGE_TAG}-latest | wc -l`
    ### Docker Backup
    - >
     if [ "$IS_LATEST" == "1" ]; then
       echo "Image Backup";
       nerdctl pull ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest;
       nerdctl tag ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-backup;
       nerdctl push ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-backup;
     fi

    ### Docker Build & Push
    - docker build . -t ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG} -f ${DOCKER_FILE_NAME} ${DOCKER_BUILD_ARGS}
    - nerdctl push ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}
    
    - nerdctl tag ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG} ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest
    - nerdctl push ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest

.template-kaniko-build:
  script:

    # AWS ECR Login
    - aws ecr get-login-password --region ${AWS_REGION} | nerdctl login --username AWS --password-stdin ${ECR_BASE_URL}

    ### Check Latest Image
    - export IS_LATEST=`aws ecr describe-images --region ${AWS_REGION} --repository-name ${DEST_ECR_IMAGE_REPO} --query imageDetails[].imageTags | grep ${DEST_ECR_IMAGE_TAG}-latest | wc -l`
    ### Docker Backup
    - >
      if [ "$IS_LATEST" == "1" ]; then
        echo "Image Backup";
        nerdctl pull ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest;
        nerdctl tag ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-latest ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-backup;
        nerdctl push ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}-backup;
      fi

    ### Kaniko Build
    - mkdir -p /kaniko/.docker
    - echo "{"credsStore":"ecr-login","credHelpers":{"$REGISTRY_URL":"ecr-login"}}" > /kaniko/.docker/config.json

    - /kaniko/executor
      --ignore-path=/var/mail
      --ignore-path=/var/spool/mail
      --context "${CI_PROJECT_DIR}"
      --build-arg BASE_IMAGE_NAME="$BASE_IMAGE_NAME"
      --build-arg BASE_IMAGE_TAG="$BASE_IMAGE_TAG"
      --dockerfile "${CI_PROJECT_DIR}/${DOCKER_FILE_NAME}"
      --destination "${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}"
      
.template-copy-docker-hub-to-ecr:
  script:
    # AWS ECR Login
    - aws ecr get-login-password --region ${AWS_REGION} | nerdctl login --username AWS --password-stdin ${ECR_BASE_URL}

    - nerdctl pull ${DOCKER_BASE_IMAGE_NAME}:${DOCKER_BASE_IMAGE_TAG}
    - nerdctl tag ${DOCKER_BASE_IMAGE_NAME}:${DOCKER_BASE_IMAGE_TAG} ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}

    - nerdctl push ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}

    - nerdctl rmi -f ${DOCKER_BASE_IMAGE_NAME}:${DOCKER_BASE_IMAGE_TAG}
    - nerdctl rmi -f ${ECR_BASE_URL}/${DEST_ECR_IMAGE_REPO}:${DEST_ECR_IMAGE_TAG}



copy-python3.12-alpine-latest:
  stage: package
  when: manual
  variables:
    DOCKER_BASE_IMAGE_NAME: python
    DOCKER_BASE_IMAGE_TAG: 3.12-alpine
    DEST_ECR_IMAGE_REPO: common/dockerhub
    DEST_ECR_IMAGE_TAG: python-3.12-alpine-latest
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-copy-docker-hub-to-ecr, script]
  only:
    - main

copy-alpine-latest:
  stage: package
  when: manual
  variables:
    DOCKER_BASE_IMAGE_NAME: alpine
    DOCKER_BASE_IMAGE_TAG: "3.18"
    DEST_ECR_IMAGE_REPO: common/dockerhub
    DEST_ECR_IMAGE_TAG: alpine-latest
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-copy-docker-hub-to-ecr, script]
  only:
    - main

copy-ubuntu-latest:
  stage: package
  when: manual
  variables:
    DOCKER_BASE_IMAGE_NAME: ubuntu
    DOCKER_BASE_IMAGE_TAG: latest
    DEST_ECR_IMAGE_REPO: common/dockerhub
    DEST_ECR_IMAGE_TAG: ubuntu-latest
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-copy-docker-hub-to-ecr, script]
  only:
    - main

copy-tomcat9-jdk17:
  stage: package
  when: manual
  variables:
    DOCKER_BASE_IMAGE_NAME: tomcat
    DOCKER_BASE_IMAGE_TAG: 9.0.102-jdk17-corretto-al2
    DEST_ECR_IMAGE_REPO: common/dockerhub
    DEST_ECR_IMAGE_TAG: tomcat9-jdk17
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-copy-docker-hub-to-ecr, script]
  only:
    - main

copy-gradle-8.13-jdk17-alpine:
  stage: package
  when: manual
  variables:
    DOCKER_BASE_IMAGE_NAME: gradle
    DOCKER_BASE_IMAGE_TAG: 8.13-jdk17-alpine
    DEST_ECR_IMAGE_REPO: common/dockerhub
    DEST_ECR_IMAGE_TAG: gradle8-jdk17-alpine
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-copy-docker-hub-to-ecr, script]
  only:
    - main

helm-docker-build:
  stage: package
  when: manual
  variables:
    DOCKER_FILE_NAME: Dockerfile-helm
    DEST_ECR_IMAGE_REPO: common/build
    DEST_ECR_IMAGE_TAG: helm
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-kaniko-build, script]
  only:
    - main

packageupdate-docker-build:
  stage: package
  when: manual
  variables:
    DOCKER_FILE_NAME: Dockerfile-packageupdate
    BASE_IMAGE_NAME: ${ECR_BASE_URL}/common/dockerhub 
    BASE_IMAGE_TAG: alpine-latest
    DEST_ECR_IMAGE_REPO: common/build
    DEST_ECR_IMAGE_TAG: pvre-package-update
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-kaniko-build, script]
  only:
    - main

jupyterlab-docker-build:
  stage: package
  when: manual
  variables:
    DOCKER_FILE_NAME: Dockerfile-jupyterlab
    DEST_ECR_IMAGE_REPO: common/build
    DEST_ECR_IMAGE_TAG: jupyter-notebook
  before_script:
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-kaniko-build, script]
  only:
    - main

kaniko-docker-build:
  stage: package
  when: manual
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_FILE_NAME: Dockerfile-kaniko
    DEST_ECR_IMAGE_REPO: common/build
    DEST_ECR_IMAGE_TAG: kaniko-debug
  before_script:
    - !reference [.template-kaniko-prebuild, script]
    - !reference [.template-prepare-ecr, script]
  script:
    - !reference [.template-kaniko-build, script]
  only:
    - main