ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

CMD ["/bin/sh"]
ARG VCS_REF=0444565
ARG KUBE_VERSION=1.23.0
ARG HELM_VERSION=3.8.2


RUN apk add --no-cache ca-certificates bash git openssh curl gettext bind-tools aws-cli openssl jq && wget -q https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl && curl -L https://git.io/get_helm.sh | bash -s -- --version v${HELM_VERSION} | bash && chmod +x /usr/local/bin/helm && chmod g+rwx /root && mkdir /config && chmod g+rwx /config && helm repo add "stable" "https://charts.helm.sh/stable" --force-update
WORKDIR /config
CMD ["/bin/sh" "-c" "bash"]