ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

ENV GRADLE_VERSION 6.5
ENV GRADLE_HOME /usr/local/gradle
ENV PATH ${PATH}:${GRADLE_HOME}/bin
ENV GRADLE_USER_HOME /gradle

WORKDIR /usr/local
RUN apk update && apk add --no-cache bash curl wget docker git tar unzip bash-completion openjdk8
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip && \
    unzip gradle-${GRADLE_VERSION}-bin.zip && \
    rm -f gradle-${GRADLE_VERSION}-bin.zip && \
    ln -s gradle-${GRADLE_VERSION} gradle && \
    echo -ne "- with Gradle ${GRADLE_VERSION}\n" >> /root/.built

RUN apk add --no-cache libstdc++ && rm -rf /var/cache/apk/*

CMD ["bash"]
