ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG} 

RUN apk update && apk add --no-cache bash bind-tools aws-cli jq nerdctl

RUN echo "aws ssm send-command --document-name \"AWS-RunShellScript\" --document-version \"1\" --targets '[{\"Key\":\"tag:ssm:package-update\",\"Values\":[\"yes\"]}]' --parameters '{\"workingDirectory\":[\"\"],\"executionTimeout\":[\"1800\"],\"commands\":[\"yum -y update\"]}' --timeout-seconds 600 --max-concurrency \"50\" --max-errors \"0\" --region ap-northeast-2" >> package_update.sh

RUN chmod +x package_update.sh

CMD ["./package_update.sh"]
