ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

USER root
RUN apt-get update && apt-get install -y \
    telnet curl wget dnsutils awscli git jq \
    && rm -rf /var/lib/apt/lists/*
USER jovyan