FROM python:3.11-bookworm

# COPY --from=gcr.io/kaniko-project/executor:debug /kaniko/executor /kaniko/executor

RUN apt-get update && apt-get install -y --no-install-recommends \
    aws-cli bash curl bind-tools jq nerdctl vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/*