ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

# FROM 202949997891.dkr.ecr.ap-northeast-2.amazonaws.com/common/dockerhub:alpine-latest
# the following line grabs /kaniko/executor from remote image
COPY --from=gcr.io/kaniko-project/executor:debug /kaniko/executor /kaniko/executor

RUN apk update && apk add --no-cache py3-pip bash curl bind-tools jq nerdctl containerd-ctr 
RUN pip3 install awscli