ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

CMD ["/bin/sh"]
ARG HELM_VERSION=3.17.1

RUN apt-get update && apk add --no-cache bash git curl bind-tools py3-pip aws-cli jq openssl \ 
&&  curl -L "https://dl.k8s.io/release/\$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl \
&& curl -L https://git.io/get_helm.sh | bash -s -- --version v${HELM_VERSION} && chmod +x /usr/local/bin/helm \
&& chmod g+rwx /root && mkdir /config && chmod g+rwx /config && helm repo add "stable" "https://charts.helm.sh/stable" --force-update
